name: ROYALTY Official Website
favicon: null
layout_spectrum: 1
typography_spectrum: 0.42327530262991786
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3144241482950747
  lightness: 0.5623270061332732
  saturation: 0.30428238259628415
  rhythmicContrast: 0.1832393268123269
purpose: []
